apiVersion: k3d.io/v1alpha3
kind: Simple
name: tilt
servers: 1
agents: 0
volumes:
  - volume: $HOME/.docker_data/postgres:/var/lib/postgresql/data
  # - volume: $HOME/.docker_data/emqx_api_keys.conf:/opt/emqx_api_keys.conf
registries:
  create:
    name: tilt
ports:
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
